"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var textrecognition = require("./textrecognition");
exports.textrecognition = textrecognition;
var barcodescanning = require("./barcodescanning");
exports.barcodescanning = barcodescanning;
var facedetection = require("./facedetection");
exports.facedetection = facedetection;
var imagelabeling = require("./imagelabeling");
exports.imagelabeling = imagelabeling;
var objectdetection = require("./objectdetection");
exports.objectdetection = objectdetection;
var landmarkrecognition = require("./landmarkrecognition");
exports.landmarkrecognition = landmarkrecognition;
var custommodel = require("./custommodel");
exports.custommodel = custommodel;
var automl = require("./automl");
exports.automl = automl;
var naturallanguageidentification = require("./naturallanguageidentification");
exports.naturallanguageidentification = naturallanguageidentification;
var translation = require("./translation");
exports.translation = translation;
var smartreply = require("./smartreply");
exports.smartreply = smartreply;
